apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv-log2
  namespace: mongo
  labels:
    type: local
spec:
  storageClassName: local-mongo-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # nfs:
  #   path: "/data/mongodb"
  #   server: 192.168.2.224
  # local:
  #   path: /data/mongodb
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - work3
  hostPath:
    path: /data/mongodb