apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv-new1
  namespace: mongo
  labels:
    type: local
spec:
  storageClassName: local-mongo-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # nfs:
  #   path: "/data/mongodb"
  #   server: 192.168.2.222
  # local:
  #   path: /data/mongodb
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - work2
  hostPath:
    path: /data/mongodb