apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv2
  namespace: mongo
  labels:
    type: local
spec:
  storageClassName: nfs2
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/data/mongo2"
    server: 192.168.2.222