kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-storage-mongo-0 #根据volumeClaimTemplates命名 pvc格式为 volumeClaimTemplates Name-pod name-序号
  namespace: mongo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs0
