apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv0
  namespace: mongo
  labels:
    type: local
spec:
  storageClassName: nfs0
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/data/mongo0"
    server: 192.168.2.222