kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-storage-mongo-1
  namespace: mongo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs1
