kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fast
  #namespace: mysql-space
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: my-nfs-sc