apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  namespace: my-space
  labels:
    type: local
spec:
  storageClassName: nfs
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/data"
    server: 192.168.2.222